version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: tailpress_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_net

  wordpress:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: tailpress_app
    restart: unless-stopped
    ports:
      - "8000:80"
      - "5173:5173"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('SMTP_HOST', 'mailhog');
        define('SMTP_PORT', 1025);
    volumes:
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db
    networks:
      - wordpress_net

  mailhog:
    image: mailhog/mailhog:latest
    container_name: tailpress_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - wordpress_net

networks:
  wordpress_net:
    driver: bridge

volumes:
  db_data:
